bucket: development
model:
  src: bs
  trg: en
  # The artifacts will be saved with the following format:
  # gs://{bucket}/models/{src}-{trg}/{name}_{task_id}/final_eval/{eval}/{service}[_{architecture}]
  service: mozilla
  architecture: tiny # Not required for non-mozilla evals.
  name: spring-2024
corpus:
  src: https://raw.githubusercontent.com/mozilla/firefox-translations-models/refs/heads/main/evaluation/bs-en/flores-dev.bs
  trg: https://raw.githubusercontent.com/mozilla/firefox-translations-models/refs/heads/main/evaluation/bs-en/flores-dev.bergamot-tiny.en
  ref: https://raw.githubusercontent.com/mozilla/firefox-translations-models/refs/heads/main/evaluation/bs-en/flores-dev.en

taskcluster:
  # The GCS bucket to upload artifacts to. The options are:
  #   - production
  #     - GCS bucket is moz-fx-translations-data--303e-prod-translations-data
  #     - preserves artifacts indefinitely
  #     - should be used for production training runs
  #   - development
  #     - GCS bucket is moz-fx-translations-data--5f91-stage-translations-data
  #     - artifacts are deleted after 30 days
  #     - should be used when artifact retention is not important
  upload-bucket: production
  worker-classes:
    default: gcp-spot
