//! Static language-tag → display-name mapping.
//!
//! Covers every language Firefox Translations currently ships (54 as of writing)
//! plus the rest of the project's canonical language database
//! (`pipeline/langs/all_autogenerated.json`), so a model added later renders a name
//! instead of its bare code. Names follow Google Cloud Translation's
//! supported-languages list (<https://docs.cloud.google.com/translate/docs/languages>)
//! for the shipped tags, with a couple named by language identity where Google's
//! page has no matching code: `zh-Hans`/`zh-Hant` → Chinese (Simplified)/(Traditional)
//! (`zh-CN`/`zh-TW`), and `nn` → Norwegian Nynorsk. Non-shipped tags take the
//! canonical DB's name. An unknown tag falls back to the code itself (see
//! [`display_name`]). Deliberately a small static table, not a display-names
//! library.

/// `(tag, display name)`, sorted by tag. Covers every language Firefox Translations
/// currently ships (54 as of writing) plus the rest of the project's canonical
/// language database, so a newly-shipped model renders a name rather than its bare
/// code. Names follow Google's list for the shipped tags (hence `bn` → "Bengali",
/// not "Bangla") and the canonical DB otherwise.
const NAMES: &[(&str, &str)] = &[
    ("af", "Afrikaans"),
    ("ar", "Arabic"),
    ("as", "Assamese"),
    ("az", "Azerbaijani"),
    ("be", "Belarusian"),
    ("bg", "Bulgarian"),
    ("bn", "Bengali"),
    ("bs", "Bosnian"),
    ("ca", "Catalan"),
    ("cs", "Czech"),
    ("cy", "Welsh"),
    ("da", "Danish"),
    ("de", "German"),
    ("el", "Greek"),
    ("en", "English"),
    ("eo", "Esperanto"),
    ("es", "Spanish"),
    ("et", "Estonian"),
    ("eu", "Basque"),
    ("fa", "Persian"),
    ("ff", "Fulah"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("ga", "Irish"),
    ("gd", "Scottish Gaelic"),
    ("gl", "Galician"),
    ("gn", "Guarani"),
    ("gu", "Gujarati"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("hr", "Croatian"),
    ("hu", "Hungarian"),
    ("hy", "Armenian"),
    ("id", "Indonesian"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("ka", "Georgian"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("kn", "Kannada"),
    ("ko", "Korean"),
    ("lt", "Lithuanian"),
    ("lv", "Latvian"),
    ("mk", "Macedonian"),
    ("ml", "Malayalam"),
    ("mr", "Marathi"),
    ("ms", "Malay"),
    ("my", "Burmese"),
    ("nb", "Norwegian Bokmål"),
    ("ne", "Nepali"),
    ("nl", "Dutch"),
    ("nn", "Norwegian Nynorsk"),
    ("no", "Norwegian"),
    ("oc", "Occitan"),
    ("or", "Odia"),
    ("pa", "Punjabi"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("si", "Sinhala"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sq", "Albanian"),
    ("sr", "Serbian"),
    ("sv", "Swedish"),
    ("ta", "Tamil"),
    ("te", "Telugu"),
    ("th", "Thai"),
    ("tl", "Tagalog"),
    ("tr", "Turkish"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("uz", "Uzbek"),
    ("vi", "Vietnamese"),
    ("xh", "Xhosa"),
    ("zh", "Chinese"),
    ("zh-Hans", "Chinese (Simplified)"),
    ("zh-Hant", "Chinese (Traditional)"),
];

/// The display name for a language tag, or the tag itself if unknown (e.g. `nn`).
pub fn display_name(tag: &str) -> &str {
    NAMES
        .iter()
        .find(|(t, _)| *t == tag)
        .map(|(_, name)| *name)
        .unwrap_or(tag)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_tags_map_to_names() {
        assert_eq!(display_name("es"), "Spanish");
        assert_eq!(display_name("en"), "English");
        assert_eq!(display_name("zh-Hans"), "Chinese (Simplified)");
        assert_eq!(display_name("zh-Hant"), "Chinese (Traditional)");
        assert_eq!(display_name("fa"), "Persian");
        // Not on Google's page by this code; named by language identity.
        assert_eq!(display_name("nn"), "Norwegian Nynorsk");
    }

    #[test]
    fn unknown_tag_falls_back_to_code() {
        assert_eq!(display_name("xx"), "xx");
        assert_eq!(display_name("qya"), "qya");
    }

    /// Every language Firefox Translations ships must resolve to a real name, never
    /// the bare-code fallback — the guard the `nn` gap slipped past. This is the
    /// shipped set from the `translations-models-v2` Remote Settings collection
    /// (the pairs `download_model.py` pulls); update it when Firefox ships more.
    #[test]
    fn covers_every_shipped_language() {
        const SHIPPED: &[&str] = &[
            "ar", "az", "be", "bg", "bn", "bs", "ca", "cs", "da", "de", "el", "en", "es", "et",
            "eu", "fa", "fi", "fr", "gl", "gu", "he", "hi", "hr", "hu", "id", "is", "it", "ja",
            "kn", "ko", "lt", "lv", "ml", "ms", "nb", "nl", "nn", "pl", "pt", "ro", "ru", "sk",
            "sl", "sq", "sr", "sv", "ta", "te", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant",
        ];
        for tag in SHIPPED {
            assert_ne!(
                display_name(tag),
                *tag,
                "shipped language `{tag}` has no display name (falls back to its code)"
            );
        }
    }

    #[test]
    fn table_is_sorted_and_unique() {
        for w in NAMES.windows(2) {
            assert!(
                w[0].0 < w[1].0,
                "NAMES must be sorted/unique: {} !< {}",
                w[0].0,
                w[1].0
            );
        }
    }
}
